### ISSUE TITLE
Review from Éric Vyncke (INT)

### ISSUE THREAD

**Issue by beurdouche** [mlswg/mls-architecture#179]
```
Éric Vyncke has entered the following ballot position for
draft-ietf-mls-architecture-10: Discuss

When responding, please keep the subject line intact and reply to all
email addresses included in the To and CC lines. (Feel free to cut this
introductory paragraph, however.)


Please refer to https://www.ietf.org/about/groups/iesg/statements/handling-ballot-positions/ 
for more information about how to handle DISCUSS and COMMENT positions.


The document, along with other ballot positions, can be found here:
https://datatracker.ietf.org/doc/draft-ietf-mls-architecture/



----------------------------------------------------------------------
DISCUSS:
----------------------------------------------------------------------


# Éric Vyncke, INT AD, comments for draft-ietf-mls-architecture-10
CC @evyncke

Thank you for the work put into this document.

I find it very difficult to understand as many concepts are not explained.
Usually, I start reading the architecture I-D before the protocol one, and this
document does not help understanding the architecture. We could even argue
whether the I-D is about architecture or about security considerations.

Please find below some blocking DISCUSS points (easy to address), some
non-blocking COMMENT points (but replies would be appreciated even if only for
my own education), and some nits.

Thanks to Tatuya Jinmei, the Internet directorate reviewer (at my request),
please consider this int-dir review with one nit worth considering:
https://datatracker.ietf.org/doc/review-ietf-mls-architecture-10-intdir-telechat-jinmei-2023-01-29/
and as noted I share Jinmei's view about the clarity of the I-D.

Please note that Dave Lawrence is the DNS directorate reviewer (at my request)
and you may want to consider this dnsdir review as well when Dave will complete
the review (no need to wait for it though):
https://datatracker.ietf.org/doc/draft-ietf-mls-architecture/reviewrequest/16998/

Special thanks to Sean Turner for the shepherd's detailed write-up including
the WG consensus *and* the justification of the intended status.

I hope that this review helps to improve the document,

Regards,

-éric

## DISCUSS

As noted in https://www.ietf.org/blog/handling-iesg-ballot-positions/, a
DISCUSS ballot is a request to have a discussion on the following topics:

### Section 6

What is a `LeafNode` ? I.e., please define what it is before using the term ;-)
Very similar issue in 5.1 for `GroupInfo`. And as noted by Jinmei "Commit" and
"Proposal".

### Section 7.1

Is it appropriate for an IETF RFC (even if informal) to qualify WireGuard and
TOR as `secure channel` ? This DISCUSS point is only to generate discussion
among the IESG during the telechat. This discuss point will be removed anyway
after the discussion.


----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------


## COMMENTS

### Abstract about 'scalable'

This document and its companion appear to demonstrate the security properties
of MLS, but do they also cover the scalability ones ? E.g., in section 2, there
is `or as large as thousands`, good number but not enough for an IETF full
remote plenary. Later in section 5, it is `groups with tens of thousands of
members`, i.e., a different order of magnitude.

### Section 2

In `The Service Provider presents ....` is it unclear to me what service it is
about ? The MLS service or the messaging service ?

Is there a reason why sometimes AS/DS acronyms are used and at other places
their expansions are used ?

`she can use to send encrypted messages to Bob and Charlie` is the message also
signed by Alice ? Hinted in section 3 but worth already warning the reader...

`join an existing group;` should "(by asking to be added)" be specified ? As
per `leave a group`.

Does the MLS group intend to extend the MLS protocol itself to support group of
moderators ? This sounds like a basic requirement to me (as a frequent
videoconf user/moderator).

### Section 4.2

Why is "Partition-tolerant" mentionned in to the classes of DS ? It seems that
it is useless to specify as a discriminator.

I find this section difficult to read, e.g., what are the "Commit" or
"Proposal" messages ? It seems that the flow is not natural.

### Section 5.4

Perhaps a mere rendering issue, but RECOMMENDATION appears in bold and is in
uppercase while it is not a normative 'RECOMMEND'. Strongly suggest to use
lowercase.

## NITS

### SEction 1

Isn't `enjoy some level of security` ambiguous or under specified ?

### Section 2

Please use the Oxford comma in `Alice, Bob and Charlie`

## Notes

This review is in the ["IETF Comments" Markdown format][ICMF], You can use the
[`ietf-comments` tool][ICT] to automatically convert this review into
individual GitHub issues.

[ICMF]: https://github.com/mnot/ietf-comments/blob/main/format.md
[ICT]: https://github.com/mnot/ietf-comments
```

**Comment by rohan-wire** [comment]
DISCUSS issues:
> ### Section 6
> 
> What is a `LeafNode` ? I.e., please define what it is before using the term ;-)
> Very similar issue in 5.1 for `GroupInfo`. And as noted by Jinmei "Commit" and
> "Proposal".
Addressed in PR #182 

> ### Section 7.1
> 
> Is it appropriate for an IETF RFC (even if informal) to qualify WireGuard and
> TOR as `secure channel` ? This DISCUSS point is only to generate discussion
> among the IESG during the telechat. This discuss point will be removed anyway
> after the discussion.
These where removed in PR #180 

several COMMENTS addressed in PR #183 

COMMENTS not addressed
- [ ] Is there a reason why sometimes AS/DS acronyms are used and at other places
their expansions are used ?
- [ ]`she can use to send encrypted messages to Bob and Charlie` is the message also
signed by Alice ? Hinted in section 3 but worth already warning the reader...
- [ ]`join an existing group;` should "(by asking to be added)" be specified ? As
per `leave a group`.
- [ ] Why is "Partition-tolerant" mentionned in to the classes of DS ? It seems that
it is useless to specify as a discriminator.
- [ ] I find [Section 4.2] difficult to read, e.g., what are the "Commit" or
"Proposal" messages ? It seems that the flow is not natural. - partially addressed in PR #182 

We had a good reason not to do anything about these:
- Perhaps a mere rendering issue, but RECOMMENDATION appears in bold and is in
uppercase while it is not a normative 'RECOMMEND'. Strongly suggest to use
lowercase. **A:** can't use normative RFC2119 language in an informational document
- Does the MLS group intend to extend the MLS protocol itself to support group of
moderators ? This sounds like a basic requirement to me (as a frequent
videoconf user/moderator). **A:** this is a feature of messaging systems, and out of scope of the MLS protocol by design.

**Comment by ekr** [comment]
After having reviewed this comment and the text, I concur that the presentation here is somewhat muddled, in a way that's not solved by just adding a terminology section. I'm going to take a pass at clarifying that, but it's probably going to take a few days.

**Comment by beurdouche** [comment]
I have verified that these comments have been processed and the fix added to the document. Thank You !
